# Exercício prático 05 - Resolução de sistemas não lineares  
### Resolução das matrizes jacobianas - matrizes das derivadas parciais
### Método de newton para sistemas não Lineares



In [2]:
def precisao_maquina():
    """Função que calcula a precisão da máquina", o número positivo em aritmética de ponto flutuante 𝜀, tal que 1 + 𝜀 >1."""
    #passo 1
    A=1
    S=2
    #passo 2
    while(S>1):
        A=A/2
        S=1+A
    prec=2*A #passo 3
    
    return prec

# def MétodoNewton_NaoLineares(M_Jacobiana,precisao = precisao_maquina() ):


In [3]:
import sympy as sym
 
#Derivatives of multivariable function
 
x1 , x2,x3 = sym.symbols('x1 x2 x3')

f1 = x1**3 -3*x1*x2**2 +1

#Differentiating partially w.r.t x
derivative_x1 = f1.diff(x1)
derivative_x2 = f1.diff(x2)

f = eval(f"{derivative_x1}{derivative_x2}")
print(f)


3*x1**2 - 6*x1*x2 - 3*x2**2


In [4]:
import numpy as np
import pandas as pd

def getMatrizJacobiana(F,n_variaveis):
    """Função que gera a matriz jacobiana de uma matriz de funções que recebe como parâmetro\n
    Parâmetros:\n
    F = matriz principal da qual se quer gerar a jacobiana\n
    Retorno:\n Matriz Jaconiana de F"""

    # pega a dimensao da matriz
    n = len(F)
    m = len(F[0])
    # gera as variáveis
    symbols = sym.symbols(f"x1:{n_variaveis+1}")
    matrizJacobiana=list()# vriável que guardará o retorno da função

    # print(n,m)
    # print(symbols)
    # percorre a matriz F
    for i in range(n):
        listaux=list()
        for j in range(m):
            f = F[i][j]
        
            # print(f"Função= {f}")

            derivadas_list =list()
            #calculo da derivada pra cada variável
            for variable in symbols:

                derivative = f.diff(variable)
                # print(f"Derivada de {variable} :{derivative}")
                if str(derivative)[0] =="-":
                    derivadas_list.append(str(derivative))
                else:
                    derivadas_list.append(" + "+str(derivative))

            #calculo da derivada parcial
            dx = " ".join(derivadas_list)
            # print(f"Derivada parcial = {dx}")
            listaux.append(eval(dx))
        # print("Lista de derivadas parciais = ",listaux)
        matrizJacobiana.append(listaux)

    return matrizJacobiana


### Exemplo de matriz jacobiana

In [5]:

#dada as funções f de 1 e f2 e a matriz F
f1 = x1**3 -3*x1*x2**2 +1
f2 = 3*x1**2*x2 - x2**3
F=[[f1],
   [f2]]

print("Matriz F(X)")
display(pd.DataFrame(F))
print("Matriz Jacobiana J(X)")
J = getMatrizJacobiana(F,2)
display(pd.DataFrame(J))

Matriz F(X)


0
0  x1**3 - 3*x1*x2**2 + 1
1      3*x1**2*x2 - x2**3

Matriz Jacobiana J(X)


0
0  3*x1**2 - 6*x1*x2 - 3*x2**2
1  3*x1**2 + 6*x1*x2 - 3*x2**2

#### Construindo a representação pra receber os valores de x

In [6]:
def F1(x):
    return np.matrix([
        [x[0]**3 -3*x[0]*x[1]**2+1,3*x[0]**2*x[1] - x[1]**3],
        [3*x[0]**2*x[1] - x[1]**3,3*x[0]**2*x[1] - x[1]**3]
    ])

def J1(x):
        return np.matrix([
         [3*x[0]**2 - 6*x[0]*x[1] - 3*x[1]**2,3*x[0]**2 + 6*x[0]*x[1] - 3*x[1]**2],
         [3*x[0]**2 + 6*x[0]*x[1] - 3*x[1]**2,3*x[0]**2 + 6*x[0]*x[1] - 3*x[1]**2]
    ])


#### Resolvendo forma 1

In [7]:
print(F1([1,2]))
print(J1([1,2]))

[[-10  -2]
 [ -2  -2]]
[[-21   3]
 [  3   3]]


#### Resolvendo forma 2

In [8]:
def GetX(F,x):
    N_variaveis = len(x)
    symbols = sym.symbols(f"x1:{N_variaveis+1}")
    dic_x={}
    for i,v in enumerate(symbols):
        dic_x[v]=x[i]

    Results=list()
    for i in range(len(F)):
        list_raux=list()
        for j in range(len(F[0])):      
            #percorre a matriz
            r=F[i][j].subs(dic_x)
            # print(r)
            list_raux.append(r)
            # print(list_raux)
        Results.append(list_raux)
    return Results


In [9]:
print(GetX(F,[1,2]))
print(GetX(J,[1,2]))

[[-10], [-2]]
[[-21], [3]]


### Exemplo 2

In [10]:
from sympy import sin,cos
f1 = x1**2 - cos(x1*x2) - 1
f2 = sin(x2) - 2*cos(x1)
F=[[f1],
   [f2]]

print("Matriz F(X)")
display(pd.DataFrame(F))
print("Matriz Jacobiana J(X)")
J = getMatrizJacobiana(F,2)
display(pd.DataFrame(J))

Matriz F(X)


0
0  x1**2 - cos(x1*x2) - 1
1     sin(x2) - 2*cos(x1)

Matriz Jacobiana J(X)


0
0  x1*sin(x1*x2) + 2*x1 + x2*sin(x1*x2)
1                   2*sin(x1) + cos(x2)

In [11]:
import math
def F2(x):
    return np.matrix([ 
        [x[0]**2 - math.cos(x[0]*x[0]) - 1],
        [math.sin(x[0]) - 2*math.cos(x[0])]])

def J2(x):
        return np.matrix([
         [x[0]*math.sin(x[0]*x[1]) + 2*x[0] + x[1]*math.sin(x[0]*x[1])],
          [2*math.sin(x[0]) + math.cos(x[1])]
          ])


In [12]:
def F(x):  
    y = np.zeros(2)  
 
    y[0] = x[0]**2 - np.cos(x[0]*x[1]) - 1  
    y[1] = np.sin(x[1]) - 2*np.cos(x[0])  
 
    return y  
 
def JF(x):  
    y = np.zeros((2,2))  
 
    y[0,0] = 2*x[0] + x[1]*np.sin(x[0]*x[1])  
    y[0,1] = x[0]*np.sin(x[0]*x[1])  
 
    y[1,0] =  2*np.sin(x[0])  
    y[1,1] = np.cos(x[1])  
 
    return y

#### Exemplo 5 -livro

In [13]:
def F5(x):  
    y = np.zeros(2)  
 
    y[0] = x[0] + x[1] - 3  
    y[1] = x[0]**2 + x[1]**2 -9
 
    return y  
 
def JF5(x):  
    y = np.zeros((2,2))  
 
    y[0,0] = 1 
    y[0,1] = 1
 
    y[1,0] =  2*x[0]
    y[1,1] = 2*x[1]  
 
    return y

In [14]:
def F4(x):  
    return np.matrix([
    x[0] + x[1] - 3 ,
    x[0]**2 + x[1]**2 -9])
 
    return y  
 
def J4(x):  
    return np.matrix([
    [1 , 1],
    [2*x[0],2*x[1]]])
 

    return y

In [15]:
print(F4([1,5]))
print(J4([1,5]))


[[ 3 17]]
[[ 1  1]
 [ 2 10]]


In [16]:
from __future__ import division  
import numpy as np  
from numpy import linalg  
 
def newton(F,JF,x0,e1=precisao_maquina(),e2=precisao_maquina(),it_max = 10000):  
    #preliminares  
    x = np.copy(x0).astype('double')
    print("Chute inicial=",x)
    k=0  
    #iteracoes  
    while (k < it_max):  
       k += 1  
       #iteracao Newton  
       delta = -np.linalg.inv(JF(x)).dot(F(x))
       print("DElTA: ",delta)
       x = x + delta
       print(f" it {k} = {x}")
       #criterio de parada  
       if (np.linalg.norm(delta,np.inf) < e1):  
           return x  
 
    raise NameError('num. max. iter. excedido.')

In [17]:
x = np.array([1.5,0.5])  
print(x)
x=x-np.linalg.inv(JF(x)).dot(F(x))
print(x)

[1.5 0.5]
[1.37745105 0.39349467]


In [18]:

R = newton(F,JF,[1.5,0.5])
print("Resposta:",R)

Chute inicial= [1.5 0.5]
DElTA:  [-0.12254895 -0.10650533]
 it 1 = [1.37745105 0.39349467]
DElTA:  [-0.02857455  0.06166443]
 it 2 = [1.3488765 0.4551591]
DElTA:  [-0.00205208  0.00512568]
 it 3 = [1.34682442 0.46028478]
DElTA:  [-1.34685877e-05  3.47457581e-05]
 it 4 = [1.34681095 0.46031953]
DElTA:  [-6.19484309e-10  1.60269389e-09]
 it 5 = [1.34681095 0.46031953]
DElTA:  [-9.94345358e-17  9.25081307e-17]
 it 6 = [1.34681095 0.46031953]
Resposta: [1.34681095 0.46031953]


In [19]:
###Resolução exemplo 5

R = newton(F5,JF5,[1,5])
print("Resposta:",R)

Chute inicial= [1. 5.]
DElTA:  [-1.625 -1.375]
 it 1 = [-0.625  3.625]
DElTA:  [ 0.53308824 -0.53308824]
 it 2 = [-0.09191176  3.09191176]
DElTA:  [ 0.08925842 -0.08925842]
 it 3 = [-2.65334194e-03  3.00265334e+00]
DElTA:  [ 0.002651 -0.002651]
 it 4 = [-2.34259734e-06  3.00000234e+00]
DElTA:  [ 2.34259551e-06 -2.34259551e-06]
 it 5 = [-1.82961514e-12  3.00000000e+00]
DElTA:  [ 1.82964754e-12 -1.82964754e-12]
 it 6 = [3.24049372e-17 3.00000000e+00]
DElTA:  [-0. -0.]
 it 7 = [3.24049372e-17 3.00000000e+00]
Resposta: [3.24049372e-17 3.00000000e+00]


In [20]:
import numpy as np
import pandas as pd

  
# Resolve o sistema triangular superior.
def SistemaTriangularSuperior(Ax,b):
  """Função que resolve um sistema linear triangular superior do tipo  𝐴𝑥 = b que recebe como parâmetro """
  n = len(b) #tamanho do vetor b
  x= [b[i]/Ax[i][i] if i == 0 else None for i in range(0,len(b))]

  x[n-1] = b[n-1]/Ax[n-1][n-1]
  iter = 0
  for i in list(range(n-1,0,-1)):
    iter+=1
    s = 0
    for j in list(range(i+1,n+1)):
      s = s + Ax[i-1][j-1]*x[j-1]

    x[i-1] = (b[i-1]-s)/(Ax[i-1][i-1])

  return [x,iter]

def EliminacaoDeGauss(A,b):
  """Função que resolve um sistema linear do tipo Ax = b que recebe como parâmetro
     Return : retorna o vetor x resultante"""
  
  # ELIMINAÇÃO DE GAUSS
  n = len(b)

  # Calculo dos pivos.
  for k in range(1,n+1):
    # PIVOTEAMENTO PARCIAL
    for i in range(k+1, len(A)+1):
      if (abs(A[i-1][k-1]) > abs(A[k-1][k-1])):
        [A[k-1], A[i-1]] = [A[i-1], A[k-1]]
        [b[k-1], b[i-1]] = [b[i-1], b[k-1]]

    # Calculo dos multiplicadores.
    for i in list(range(k+1,n+1)):
      m = A[i-1][k-1]/A[k-1][k-1]
      A[i-1][k-1] = 0
      
      # Atualizar demais valores da linha
      for j in list(range(k+1,n+1)):
        A[i-1][j-1] = A[i-1][j-1]-m*A[k-1][j-1]
      b[i-1] = b[i-1] - m*b[k-1]

  # print("depois da eliminação\n Ax =  ",Ax2,"\nb = ",b2)
  x = SistemaTriangularSuperior(A,b)
  return(x)

In [126]:
def Newton_N_Lineares(F,J,x0,e1=precisao_maquina(),e2=precisao_maquina(),it_max=10000):  
    verifica_precisao =np.max(F(x0)) 

    if verifica_precisao < e1:
        return(x0)
    xk=x0
    # print("Chute Inicial : ",F(x0))
    k=0

    while(verifica_precisao>e2 and k<it_max):
        # print(f"\n{k}\n")
        # print(f"J(x{k}) = ",J(xk).tolist())
        # print(f"-F(x{k})",(-F(xk)[0]).tolist()[0])

        s= np.matrix(EliminacaoDeGauss(J(xk).tolist(),(-F(xk)[0]).tolist()[0])[0])
        # print("s = ",s)
        xk=np.matrix(xk)
        xkp1= xk+s # calcula 0 x^k+1
        # print(f"x{k+1} = {xkp1}")

        if abs(np.max(np.abs(xkp1-xk))) < e2:
            # print("menor")
            return xkp1.tolist()[0],k
        
        # print(f"{np.max(np.abs(xkp1-xk))}> e2")
        k+=1
        xk=xkp1.tolist()[0] # atualiza o xk pra ser xk+1
        # print(xk)
        verifica_precisao =np.max(F(xk))

    return xk,k

In [127]:
print(Newton_N_Lineares(F4,J4,[1,5])) 

([1.1567124056158726e-16, 3.0], 6)


In [91]:
Newton_N_Lineares(F4,J4,[1,5])

Chute Inicial :  [[ 3 17]]


[1, 5]

### Exemplo 2

In [ ]:
#dada as funções f de 1 e f2 e a matriz F
f1 = x1**2/3 + x2**2 - 1
f2 = x1**2 + x2**2/4 - 1
F=[[f1],
   [f2]]

print("Matriz F(X)")
display(pd.DataFrame(F))
print("Matriz Jacobiana J(X)")
display(pd.DataFrame(getMatrizJacobiana(F,2)))

Matriz F(X)


0
0  x1**2/3 + x2**2 - 1
1  x1**2 + x2**2/4 - 1

Matriz Jacobiana J(X)


0
0  2*x1/3 + 2*x2
1    2*x1 + x2/2

In [ ]:
Newton_N_Lineares(F1,J1,[1,2])

[[-10  -2]
 [ -2  -2]]
[[-20  -4]
 [ -4  -4]]
chute inicial[0][0] [[-10  -2]]
chute inicial[1][0] [[-2 -2]]
